import {
  SiReact,
  SiTypescript,
  SiJavascript,
  SiNextdotjs,
  SiVite,
  SiTailwindcss,
  SiHtml5,
  SiRedux,
  SiReactquery,
  SiFigma,
  SiEslint,
  SiStorybook,
  SiTestinglibrary,
  SiCypress,
  SiNodedotjs,
  SiMongodb,
  SiDocker,
  SiNpm,
  SiPnpm,
  SiYarn,
  SiGit,
  SiGraphql,
  SiFirebase,
  SiVercel,
  SiNetlify,
  SiGithubactions,
  SiCloudflare,
  SiContentful,
  SiMixpanel,
  SiWordpress,
  SiSlack,
  SiLinear,
  SiPostman,
  SiGooglechrome,
} from 'react-icons/si'
import { HiOutlineCodeBracket, HiOutlineDevicePhoneMobile, HiOutlineGlobeAlt, HiOutlineBeaker, HiOutlineCog, HiOutlineServerStack, HiOutlineUserGroup } from 'react-icons/hi2'

const iconSize = 18

const brandColors: Record<string, string> = {
  React: '#61DAFB',
  TypeScript: '#3178C6',
  JavaScript: '#F7DF1E',
  'Next.js': '#000000',
  Vite: '#646CFF',
  'Tailwind CSS': '#06B6D4',
  'HTML/CSS': '#E34F26',
  Redux: '#764ABC',
  'React Query': '#FF4154',
  Figma: '#F24E1E',
  Git: '#F05032',
  Firebase: '#FFCA28',
  'Node.js': '#339933',
  npm: '#CB3837',
  pnpm: '#F69220',
  Yarn: '#2C8EBB',
  GraphQL: '#E10098',
  Vercel: '#000000',
  Netlify: '#00C7B7',
  Slack: '#4A154B',
  Linear: '#5E6AD2',
  Postman: '#FF6C37',
  'Chrome DevTools': '#4285F4',
  ESLint: '#4B32C3',
  Storybook: '#FF4785',
  MongoDB: '#47A248',
  Docker: '#2496ED',
  'GitHub Actions': '#2088FF',
  Cloudflare: '#F38020',
  Contentful: '#2478CC',
  Mixpanel: '#7856FF',
  WordPress: '#21759B',
}

const neutralIcon = (Icon: React.ComponentType<{ size?: number; className?: string }>) => (
  <Icon size={iconSize} className="text-slate-500 dark:text-slate-400" />
)

const skillIcons: Record<string, React.ReactElement> = {
  React: <SiReact size={iconSize} color={brandColors.React} />,
  TypeScript: <SiTypescript size={iconSize} color={brandColors.TypeScript} />,
  JavaScript: <SiJavascript size={iconSize} color={brandColors.JavaScript} />,
  'Next.js': <SiNextdotjs size={iconSize} color={brandColors['Next.js']} />,
  Vite: <SiVite size={iconSize} color={brandColors.Vite} />,
  'Tailwind CSS': <SiTailwindcss size={iconSize} color={brandColors['Tailwind CSS']} />,
  'HTML/CSS': <SiHtml5 size={iconSize} color={brandColors['HTML/CSS']} />,
  Redux: <SiRedux size={iconSize} color={brandColors.Redux} />,
  Zustand: neutralIcon(HiOutlineCodeBracket),
  'React Query': <SiReactquery size={iconSize} color={brandColors['React Query']} />,
  Figma: <SiFigma size={iconSize} color={brandColors.Figma} />,
  ESLint: <SiEslint size={iconSize} color={brandColors.ESLint} />,
  Storybook: <SiStorybook size={iconSize} color={brandColors.Storybook} />,
  'React Testing Library': <SiTestinglibrary size={iconSize} color="#E33332" />,
  Cypress: <SiCypress size={iconSize} color="#17202C" />,
  'Responsive Design': <HiOutlineDevicePhoneMobile size={iconSize} className="text-slate-500 dark:text-slate-400" />,
  'Node.js': <SiNodedotjs size={iconSize} color={brandColors['Node.js']} />,
  MongoDB: <SiMongodb size={iconSize} color={brandColors.MongoDB} />,
  Docker: <SiDocker size={iconSize} color={brandColors.Docker} />,
  npm: <SiNpm size={iconSize} color={brandColors.npm} />,
  pnpm: <SiPnpm size={iconSize} color={brandColors.pnpm} />,
  Yarn: <SiYarn size={iconSize} color={brandColors.Yarn} />,
  Git: <SiGit size={iconSize} color={brandColors.Git} />,
  'REST APIs': <HiOutlineGlobeAlt size={iconSize} className="text-slate-500 dark:text-slate-400" />,
  GraphQL: <SiGraphql size={iconSize} color={brandColors.GraphQL} />,
  Firebase: <SiFirebase size={iconSize} color={brandColors.Firebase} />,
  Vercel: <SiVercel size={iconSize} color={brandColors.Vercel} />,
  Netlify: <SiNetlify size={iconSize} color={brandColors.Netlify} />,
  'GitHub Actions': <SiGithubactions size={iconSize} color={brandColors['GitHub Actions']} />,
  Cloudflare: <SiCloudflare size={iconSize} color={brandColors.Cloudflare} />,
  Slack: <SiSlack size={iconSize} color={brandColors.Slack} />,
  Teams: neutralIcon(HiOutlineUserGroup),
  Linear: <SiLinear size={iconSize} color={brandColors.Linear} />,
  Postman: <SiPostman size={iconSize} color={brandColors.Postman} />,
  Cursor: neutralIcon(HiOutlineCodeBracket),
  Contentful: <SiContentful size={iconSize} color={brandColors.Contentful} />,
  Mixpanel: <SiMixpanel size={iconSize} color={brandColors.Mixpanel} />,
  WordPress: <SiWordpress size={iconSize} color={brandColors.WordPress} />,
  'Chrome DevTools': <SiGooglechrome size={iconSize} color={brandColors['Chrome DevTools']} />,
  Testing: <HiOutlineBeaker size={iconSize} className="text-slate-500 dark:text-slate-400" />,
  'CI/CD': <HiOutlineCog size={iconSize} className="text-slate-500 dark:text-slate-400" />,
  Systems: <HiOutlineServerStack size={iconSize} className="text-slate-500 dark:text-slate-400" />,
}

const defaultIcon = <HiOutlineCodeBracket size={iconSize} className="text-slate-500 dark:text-slate-400" />

export function SkillIcon({ name }: { name: string }) {
  const icon = skillIcons[name] ?? defaultIcon
  return <span className="inline-flex items-center justify-center flex-shrink-0" aria-hidden>{icon}</span>
}
